package com.example.ecommerce.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * This class represents an agent in the e-commerce platform.
 * An agent typically handles customer interactions and support.
 */
@Entity
public class Agent {

    /**
     * The unique identifier for the agent.
     * It is automatically generated by the persistence provider.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long agentId;

    /**
     * The name of the agent.
     */
    private String name;

    // Getters and setters

    /**
     * Gets the unique identifier for the agent.
     * @return the agent's id
     */
    public Long getAgentId() {
        return agentId;
    }

    /**
     * Sets the unique identifier for the agent.
     * @param agentId the agent's id
     */
    public void setAgentId(Long agentId) {
        this.agentId = agentId;
    }

    /**
     * Gets the name of the agent.
     * @return the agent's name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the agent.
     * @param name the agent's name
     */
    public void setName(String name) {
        this.name = name;
    }
}
