package com.example.ecommerce.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * This class represents a customer in the e-commerce platform.
 */
@Entity
public class Customer {

    /**
     * The unique identifier for the customer.
     * It is automatically generated by the persistence provider.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long customerId;

    /**
     * The name of the customer.
     */
    private String name;

    // Getters and setters

    /**
     * Gets the unique identifier for the customer.
     * @return the customer's id
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * Sets the unique identifier for the customer.
     * @param customerId the customer's id
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * Gets the name of the customer.
     * @return the customer's name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the customer.
     * @param name the customer's name
     */
    public void setName(String name) {
        this.name = name;
    }
}
