package com.example.ecommerce.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * This class represents a product in the e-commerce platform.
 */
@Entity
public class Product {

    /**
     * The unique identifier for the product.
     * It is automatically generated by the persistence provider.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long productId;

    /**
     * The name of the product.
     */
    private String name;

    /**
     * The price of the product.
     */
    private Double price;

    // Getters and setters

    /**
     * Gets the unique identifier for the product.
     * @return the product's id
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * Sets the unique identifier for the product.
     * @param productId the product's id
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * Gets the name of the product.
     * @return the product's name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the product.
     * @param name the product's name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the price of the product.
     * @return the product's price
     */
    public Double getPrice() {
        return price;
    }

    /**
     * Sets the price of the product.
     * @param price the product's price
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}
